"""Initial LineSec 2+ schema

Revision ID: 7ddd606ac30e
Revises: 
Create Date: 2026-09-08 22:59:20.317681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ddd606ac30e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_event_id'), 'audit_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_table('policies',
    sa.Column('policy_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rules_json', sa.Text(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_index(op.f('ix_policies_name'), 'policies', ['name'], unique=True)
    op.create_index(op.f('ix_policies_policy_id'), 'policies', ['policy_id'], unique=False)
    op.create_table('repositories',
    sa.Column('repository_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('default_branch', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('criticality', sa.String(), nullable=True),
    sa.Column('internet_exposed', sa.Boolean(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('repository_id')
    )
    op.create_index(op.f('ix_repositories_name'), 'repositories', ['name'], unique=True)
    op.create_index(op.f('ix_repositories_repository_id'), 'repositories', ['repository_id'], unique=False)
    op.create_table('risk_acceptances',
    sa.Column('acceptance_id', sa.String(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('acceptance_id')
    )
    op.create_index(op.f('ix_risk_acceptances_acceptance_id'), 'risk_acceptances', ['acceptance_id'], unique=False)
    op.create_index(op.f('ix_risk_acceptances_finding_id'), 'risk_acceptances', ['finding_id'], unique=False)
    op.create_index(op.f('ix_risk_acceptances_task_id'), 'risk_acceptances', ['task_id'], unique=False)
    op.create_table('vulnerability_intel',
    sa.Column('intel_id', sa.String(), nullable=False),
    sa.Column('cve_id', sa.String(), nullable=True),
    sa.Column('package', sa.String(), nullable=True),
    sa.Column('ecosystem', sa.String(), nullable=True),
    sa.Column('epss_score', sa.Float(), nullable=True),
    sa.Column('epss_percentile', sa.Float(), nullable=True),
    sa.Column('cisa_kev', sa.Boolean(), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('intel_id')
    )
    op.create_index(op.f('ix_vulnerability_intel_cve_id'), 'vulnerability_intel', ['cve_id'], unique=False)
    op.create_index(op.f('ix_vulnerability_intel_intel_id'), 'vulnerability_intel', ['intel_id'], unique=False)
    op.create_index(op.f('ix_vulnerability_intel_package'), 'vulnerability_intel', ['package'], unique=False)
    op.create_table('remediation_tasks',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('repository_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('package', sa.String(), nullable=True),
    sa.Column('ecosystem', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('target_version', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('safety_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.repository_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_remediation_tasks_repository_id'), 'remediation_tasks', ['repository_id'], unique=False)
    op.create_index(op.f('ix_remediation_tasks_status'), 'remediation_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_remediation_tasks_task_id'), 'remediation_tasks', ['task_id'], unique=False)
    op.create_index(op.f('ix_remediation_tasks_title'), 'remediation_tasks', ['title'], unique=False)
    op.create_index('ix_tasks_status_priority', 'remediation_tasks', ['status', 'priority'], unique=False)
    op.create_table('scans',
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('repository_id', sa.String(), nullable=True),
    sa.Column('scanner', sa.String(), nullable=True),
    sa.Column('scanner_type', sa.String(), nullable=True),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_findings', sa.Integer(), nullable=True),
    sa.Column('new_findings', sa.Integer(), nullable=True),
    sa.Column('resolved_findings', sa.Integer(), nullable=True),
    sa.Column('regressed_findings', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.repository_id'], ),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_index(op.f('ix_scans_repository_id'), 'scans', ['repository_id'], unique=False)
    op.create_index(op.f('ix_scans_scan_id'), 'scans', ['scan_id'], unique=False)
    op.create_index(op.f('ix_scans_scanner'), 'scans', ['scanner'], unique=False)
    op.create_table('findings',
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('repository_id', sa.String(), nullable=True),
    sa.Column('scan_id', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('scanner', sa.String(), nullable=True),
    sa.Column('scanner_type', sa.String(), nullable=True),
    sa.Column('vulnerability_name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('cve', sa.String(), nullable=True),
    sa.Column('cwe', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('package', sa.String(), nullable=True),
    sa.Column('ecosystem', sa.String(), nullable=True),
    sa.Column('installed_version', sa.String(), nullable=True),
    sa.Column('fixed_version', sa.String(), nullable=True),
    sa.Column('remediation_status', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('service_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('remediation_plan', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.repository_id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['remediation_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('finding_id')
    )
    op.create_index(op.f('ix_findings_cve'), 'findings', ['cve'], unique=False)
    op.create_index(op.f('ix_findings_finding_id'), 'findings', ['finding_id'], unique=False)
    op.create_index(op.f('ix_findings_fingerprint'), 'findings', ['fingerprint'], unique=False)
    op.create_index('ix_findings_fingerprint_repo', 'findings', ['fingerprint', 'repository_id'], unique=False)
    op.create_index(op.f('ix_findings_remediation_status'), 'findings', ['remediation_status'], unique=False)
    op.create_index(op.f('ix_findings_repository_id'), 'findings', ['repository_id'], unique=False)
    op.create_index(op.f('ix_findings_scan_id'), 'findings', ['scan_id'], unique=False)
    op.create_index(op.f('ix_findings_scanner'), 'findings', ['scanner'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_index('ix_findings_status_severity', 'findings', ['status', 'severity'], unique=False)
    op.create_index(op.f('ix_findings_task_id'), 'findings', ['task_id'], unique=False)
    op.create_index(op.f('ix_findings_tool_name'), 'findings', ['tool_name'], unique=False)
    op.create_index(op.f('ix_findings_vulnerability_name'), 'findings', ['vulnerability_name'], unique=False)
    op.create_table('fix_plans',
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('ecosystem', sa.String(), nullable=True),
    sa.Column('package', sa.String(), nullable=True),
    sa.Column('current_version', sa.String(), nullable=True),
    sa.Column('target_version', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('safety_level', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('verification_steps', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['remediation_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_fix_plans_plan_id'), 'fix_plans', ['plan_id'], unique=False)
    op.create_index(op.f('ix_fix_plans_task_id'), 'fix_plans', ['task_id'], unique=True)
    op.create_table('task_decisions',
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('business_impact', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('estimated_effort', sa.String(), nullable=True),
    sa.Column('deployment_risk', sa.String(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('verification_guidance', sa.Text(), nullable=True),
    sa.Column('ai_enriched', sa.Boolean(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['remediation_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index(op.f('ix_task_decisions_decision_id'), 'task_decisions', ['decision_id'], unique=False)
    op.create_index(op.f('ix_task_decisions_task_id'), 'task_decisions', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_decisions_task_id'), table_name='task_decisions')
    op.drop_index(op.f('ix_task_decisions_decision_id'), table_name='task_decisions')
    op.drop_table('task_decisions')
    op.drop_index(op.f('ix_fix_plans_task_id'), table_name='fix_plans')
    op.drop_index(op.f('ix_fix_plans_plan_id'), table_name='fix_plans')
    op.drop_table('fix_plans')
    op.drop_index(op.f('ix_findings_vulnerability_name'), table_name='findings')
    op.drop_index(op.f('ix_findings_tool_name'), table_name='findings')
    op.drop_index(op.f('ix_findings_task_id'), table_name='findings')
    op.drop_index('ix_findings_status_severity', table_name='findings')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_scanner'), table_name='findings')
    op.drop_index(op.f('ix_findings_scan_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_repository_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_remediation_status'), table_name='findings')
    op.drop_index('ix_findings_fingerprint_repo', table_name='findings')
    op.drop_index(op.f('ix_findings_fingerprint'), table_name='findings')
    op.drop_index(op.f('ix_findings_finding_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_cve'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_scans_scanner'), table_name='scans')
    op.drop_index(op.f('ix_scans_scan_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_repository_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index('ix_tasks_status_priority', table_name='remediation_tasks')
    op.drop_index(op.f('ix_remediation_tasks_title'), table_name='remediation_tasks')
    op.drop_index(op.f('ix_remediation_tasks_task_id'), table_name='remediation_tasks')
    op.drop_index(op.f('ix_remediation_tasks_status'), table_name='remediation_tasks')
    op.drop_index(op.f('ix_remediation_tasks_repository_id'), table_name='remediation_tasks')
    op.drop_table('remediation_tasks')
    op.drop_index(op.f('ix_vulnerability_intel_package'), table_name='vulnerability_intel')
    op.drop_index(op.f('ix_vulnerability_intel_intel_id'), table_name='vulnerability_intel')
    op.drop_index(op.f('ix_vulnerability_intel_cve_id'), table_name='vulnerability_intel')
    op.drop_table('vulnerability_intel')
    op.drop_index(op.f('ix_risk_acceptances_task_id'), table_name='risk_acceptances')
    op.drop_index(op.f('ix_risk_acceptances_finding_id'), table_name='risk_acceptances')
    op.drop_index(op.f('ix_risk_acceptances_acceptance_id'), table_name='risk_acceptances')
    op.drop_table('risk_acceptances')
    op.drop_index(op.f('ix_repositories_repository_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_name'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_policies_policy_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_name'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
