import os
import json
from typing import List, Any
import requests
from ai.base import AIAnalysisProvider, TaskDecisionData
from ai.sanitizer import PromptSanitizer

class GeminiAIProvider(AIAnalysisProvider):
    """
    Google Gemini AI Reasoning Provider using structured JSON mode.
    """

    def __init__(self, model_name: str = "gemini-2.5-flash"):
        self.model_name = model_name
        self.api_key = os.getenv("GEMINI_API_KEY")

    @property
    def name(self) -> str:
        return "gemini"

    def is_available(self) -> bool:
        return bool(self.api_key and len(self.api_key) > 5)

    def analyze_task(
        self,
        task: Any,
        findings: List[Any],
        environment: str = "development",
        criticality: str = "MEDIUM"
    ) -> TaskDecisionData:
        if not self.is_available():
            raise RuntimeError("GEMINI_API_KEY is not configured or invalid")

        # Build sanitized input summary
        findings_summary = "\n".join([
            f"- {getattr(f, 'vulnerability_name', 'Unknown')}: Severity={getattr(f, 'severity', 'UNKNOWN')}, File={getattr(f, 'file_path', 'unknown')}:{getattr(f, 'line_number', 0)}"
            for f in findings[:10]
        ])

        prompt = PromptSanitizer.build_structured_prompt(
            task_title=getattr(task, "title", "Security Task"),
            package=getattr(task, "package", "N/A"),
            target_version=getattr(task, "target_version", "latest"),
            findings_summary=findings_summary,
            environment=environment,
            criticality=criticality
        )

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model_name}:generateContent?key={self.api_key}"
        headers = {"Content-Type": "application/json"}
        payload = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {
                "response_mime_type": "application/json",
                "temperature": 0.2
            }
        }

        response = requests.post(url, headers=headers, json=payload, timeout=10)
        if response.status_code != 200:
            raise RuntimeError(f"Gemini API returned status {response.status_code}: {response.text}")

        res_json = response.json()
        candidates = res_json.get("candidates", [])
        if not candidates:
            raise ValueError("No candidate output generated by Gemini")

        raw_text = candidates[0].get("content", {}).get("parts", [{}])[0].get("text", "{}")
        parsed = json.loads(raw_text)

        return TaskDecisionData(
            summary=parsed.get("summary", "AI-generated vulnerability analysis"),
            root_cause=parsed.get("root_cause", "Underlying software vulnerability"),
            business_impact=parsed.get("business_impact", "Potential security exposure"),
            recommended_action=parsed.get("recommended_action", "Apply recommended patch"),
            estimated_effort=parsed.get("estimated_effort", "1 hour"),
            deployment_risk=parsed.get("deployment_risk", "LOW"),
            reasoning=parsed.get("reasoning", "Analysis based on published security advisories"),
            verification_guidance=parsed.get("verification_guidance", "Run security scans post-fix"),
            priority=getattr(task, "priority", "P2"),
            confidence=0.95,
            provider="gemini",
            model=self.model_name,
            ai_enriched=True
        )
